//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aytesoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string B2bCode { get; set; }
        public string Adress { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string TaxOffice { get; set; }
        public Nullable<int> TaxNumber { get; set; }
        public string Mail { get; set; }
        public string Status { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Gsm1 { get; set; }
        public string Gsm2 { get; set; }
        public string Fax1 { get; set; }
        public string Notes { get; set; }
        public Nullable<int> NumberOfUser { get; set; }
        public Nullable<int> NumberOfUserAndroid { get; set; }
        public Nullable<int> NumberOfUserIos { get; set; }
        public string RiskLimit { get; set; }
        public string CreditLimit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
