//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aytesoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public string productcode { get; set; }
        public string productname { get; set; }
        public string customerid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> total { get; set; }
        public string date { get; set; }
        public Nullable<int> discountrate { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> orderno { get; set; }
    }
}
